all: unified-types\
     type-casting\
     collections\
     collections-immutable\
     collections-mutable\
     collections-legend
unified-types:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
type-casting:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
collections:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
collections-immutable:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
collections-mutable:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
collections-legend:
	dot -Tsvg $@-diagram.dot -o $@-diagram.svg
